---
  - hosts: all
    become: true
    gather_facts: false
    tasks:
      - name: "Install basic software"
        apt:
          package:
            - htop
            - finger
          state: present

      - name: "Install provisioning cronjob"
        ansible.builtin.cron:
          name: "Provisioning"
          minute: "*/10"
          job: "/usr/bin/ansible-pull -U https://github.com/maxraab/ansible-pull-test.git provision.yml > /var/log/ansible-provisioning.log 2>&1"

      - name: "Reboot the machine"
        reboot:

      - name: "APT ful upgrade"
        apt:
          autoclean: yes
          autoremove: yes
          purge: yes
          update_cache: yes
          upgrade: full

  - hosts: webserver
    become: true
    gather_facts: false
    tasks:
      - name: "create webserver config"
        copy:
          content: "this is a webserver"
          dest: /root/webserver.config
          group: root
          owner: root
          mode: 0555

  - hosts: dbserver
    become: true
    gather_facts: false
    tasks:
      - name: "create database config"
        copy:
          content: "this is a database"
          dest: /root/database.config
          group: root
          owner: root
          mode: 0555
